paths:
  - Configuration/TypoScript
sniffs:
  - class: Indentation
    parameters:
      useSpaces: true
      indentPerLevel: 4
      indentConditions: true
  - class: RepeatingRValue
    disabled: true
